### ISSUE TITLE
Works in wamp but not in live server

### ISSUE THREAD

**Issue by mdimitris** [hparfr/prestashopBridge#14]
Hello! 
I have a custom php/mysql application (not symfony or any other framework) 

I managed to make it work in wamp server but in live server (linux) it throws the following error:

> mod_fcgid: stderr: PHP Fatal error: Class 'Hpar\ \PrestashopBridge\ \PrestashopBridge' not found in /var/www/vhosts/exaample.com/httpdocs/demo/prestaconnect.php on line 10, referer: http://demo.example.com/index.php

I think it is because for some reason in linux the slashes are duplicated. Or is it for some other reason?How can I solve it? I am desperate...

I attach the code:

`require 'Hpar/PrestashopBridge/vendor/autoload.php';
use Hpar\PrestashopBridge\PrestashopBridge;

$email = "jim369@gmail.com";
$lastname = "Doe";
$firstname = "John";
$prestaBridge = new PrestashopBridge('/var/www/vhosts/example.com/httpdocs/eshop/', 1);

if (!$prestaBridge->userExist($email))
    $prestaBridge->createUser($email, $lastname, $firstname);

$prestaBridge->login($email);
return $prestaBridge->redirect('http://example.com');

?>`

thank you

**Comment by hparfr** [comment]
Hi,

There is a typo in "/var/www/vhosts/ex**AA**mple.com".

**Comment by mdimitris** [comment]
Thanks for the quick answer...Where is the typo? I cant see it!!
Also one more question: Can it work with subdomains (same server, and the subdomain "belongs" to main domain where prestashop is)

**Comment by mdimitris** [comment]
I also receive this 

`mod_fcgid: stderr: PHP Fatal error: Call to undefined method Hpar\ \PrestashopBridge\ \PrestashopBridge::redirect() in /var/www/vhosts/example.com/httpdocs/demo/prestaconnect.php on line 19, referer: http://demo.example.com/index.php`

and when I replace $prestaBridge->redirect('http://example.com'); with $this->redirect('http://example.com');

`mod_fcgid: stderr: PHP Fatal error: Using $this when not in object context in /var/www/vhosts/example.com/httpdocs/demo/prestaconnect.php on line 19, referer: http://demo.example.com/index.php`

**Comment by hparfr** [comment]
> Thanks for the quick answer...Where is the typo? I cant see it!!

On line $prestaBridge = new PrestashopBridge('/var/www/vhosts/example.com/httpdocs/eshop/', 1);
from the file /var/www/vhosts/exaample.com/httpdocs/demo/prestaconnect.php 

> Also one more question: Can it work with subdomains (same server, and the subdomain "belongs" to main domain where prestashop is)

No you can't. It comes from a restriction of the browser.

> mod_fcgid: stderr: PHP Fatal error: Call to undefined method

There is no redirect method in the lib. In the example redirect was provided by the application (not the lib).

**Comment by mdimitris** [comment]
I suppose then in subfolder it will work? e.g. eshop in example.com and application in example.com/subfolder?

Thanks again!

**Comment by hparfr** [comment]
Yes.
