### ISSUE TITLE
Problems with Prestashop 1.7

### ISSUE THREAD

**Issue by maxthev** [hparfr/prestashopBridge#15]
Hi !

I'm trying to use this scrip in a Symfony 3.2 project with Prestashop 1.7 and it's currently not working.

The first issue is that if I use the whole script you made, the \CompareProduct is not found (it seems it does not exist anymore)

```php
$ctx->cookie->id_compare = isset($ctx->cookie->id_compare) ? $ctx->cookie->id_compare : \CompareProduct::getIdCompareByIdCustomer($customer->id);
```
I tried commenting this code, a cookie is created but it's not login in Prestashop.

So i searched for a newer version of this and i found this function in Presta 1.7 :

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php#L305

Now I'm trying to adapt your script with this new code but i'm facing 2 main errors when I test something :

```
UndefinedMethodException in appDevDebugProjectContainer.php line 3866:
Attempted to call an undefined method named "setDisplayOptions" of class "Symfony\Component\VarDumper\Dumper\HtmlDumper".
```

Or

```
UndefinedMethodException in UnitOfWork.php line 1131:
Attempted to call an undefined method named "hasNode" of class "Doctrine\ORM\Internal\CommitOrderCalculator".
```

So if you have any idea of how to make your script work with Presta 1.7, it would very nice :)

Which version of Prestashop are working with this scrip ? (1.6 maybe ?)

Thank you in advance.

**Comment by hparfr** [comment]
Hi,

It was written for an now old version of prestashop (it was the latest version at the time).
I guess your new bugs in setDisplayOptions and hasNode are not related to this lib.

I do not maintain anymore this lib.
