### ISSUE TITLE
Can I use this without Synfony?

### ISSUE THREAD

**Issue by xabikip** [hparfr/prestashopBridge#3]
I have my own PHP/MySQL application, and i would know if it'a possible use your bridge, and if you can put any example how to use with pure PHP application.

Thanks,

**Comment by hparfr** [comment]
Yes.
The only dependency is to HttpFoundation component (it's a standalone component).

**Comment by xabikip** [comment]
ok, could you put an example of how to use without Symfony? to execute pure PHP application.

Thanks,

**Comment by hparfr** [comment]
```php
<?php 

//[...]
use Hpar\PrestashopBridge\PrestashopBridge;

//[...]
$email = "john.doe@prestashop.com";
$lastname = "Doe";
$firstname = "John";
$prestaBridge = new PrestashopBridge('/path/to/prestashop/', 1);

//[...]
if (!$prestaBridge->userExist($email))
	$prestaBridge->createUser($email, $lastname, $firstname);

$prestaBridge->login($email);

?>
```

**Comment by xabikip** [comment]
Sorry, but i'm new with symfony and composer.
Is that folder structure well?

|_/folder1
|_/folder2
|_/vendor
   |_/hpar
      |_/prestashop_bridge
         PrestashopBridge.php
   |_/symfony
      |_/http-foundation
         |_Symfony
             |_/component
                |_/HttpFoundation
                    file1.php
                    file2.php
                    Bridge.php
presta_login.php(here I use your bridge)

I have this error: PHP Fatal error:  Class 'Hpar\\PrestashopBridge\\PrestashopBridge' not found in /var/www/resourcespace/presta_login.php on line 9

Line 9 = use Hpar\PrestashopBridge\PrestashopBridge;

I have PHP 5.4

**Comment by xabikip** [comment]
Sorry, but i'm new with symfony and composer.
Is that folder structure well?

-/folder1
-/folder2
-/vendor
  -/hpar
    -/prestashop_bridge
      -PrestashopBridge.php
  -/symfony
    -/http-foundation
      -/Symfony
        -/component
          -/HttpFoundation
             file1.php
             file2.php
             Bridge.php
presta_login.php(here I use your bridge)

I have this error: PHP Fatal error: Class 'Hpar\PrestashopBridge\PrestashopBridge' not found in /var/www/resourcespace/presta_login.php on line 9

Line 9 = use Hpar\PrestashopBridge\PrestashopBridge;

I have PHP 5.4

**Comment by xabikip** [comment]
Sorry, but i'm new with symfony and composer.
Is that folder structure well?


/Users/xabipiko/Desktop/folder.png

presta_login.php(is were I use your bridge) 

I have this error: PHP Fatal error: Class 'Hpar\PrestashopBridge\PrestashopBridge' not found in /var/www/resourcespace/presta_login.php on line 9

Line 9 = use Hpar\PrestashopBridge\PrestashopBridge;

I have PHP 5.4

**Comment by xabikip** [comment]
Sorry, but i'm new with symfony and composer.
Is that folder structure well?

![folder](https://cloud.githubusercontent.com/assets/1109793/6459165/51dd88aa-c18c-11e4-8b1b-d22e8ab324be.png)


presta_login.php(is were I use your bridge)

I have this error: PHP Fatal error: Class 'Hpar\PrestashopBridge\PrestashopBridge' not found in /var/www/resourcespace/presta_login.php on line 9

Line 9 = use Hpar\PrestashopBridge\PrestashopBridge;

I have PHP 5.4

Thanks for your help,

**Comment by hparfr** [comment]
You have to include the autoloader in the begining of your script.

```php
require 'vendor/autoload.php';
```
https://getcomposer.org/doc/00-intro.md#autoloading

**Comment by xabikip** [comment]
ok, that's right! 

Thanks very much ;-)

**Comment by greekbatter** [comment]
Could you give me an example of autoload.php? I still try to figure out how I can create it...
