### ISSUE TITLE
Problems with addToCurrentCart

### ISSUE THREAD

**Issue by xabikip** [hparfr/prestashopBridge#4]
Hi,

I`m using the function addToCurrentCart() to add aproduct, but i have an error. PHP Fatal error:  Call to a member function getProductCustomization() on a non-object in /var/www/prestashop/vendor/hpar/prestashop-bridge/PrestashopBridge.php on line 140

I debbug line by line and when create the context $ctx = \Context::getContext(); in this function, i see that the cart is empty.

That's what I'm doing wrong?

This is my code where I use addToCurrentCart() function:
require 'vendor/autoload.php';
use Hpar\PrestashopBridge\PrestashopBridge;
$id_product = $_POST["product"];
$ref = $_POST["ref"];
$prestaBridge = new PrestashopBridge('/var/www/prestashop', 1);
$prestaBridge->addToCurrentCart($id_product, 1, $ref);

Thanks very much,

**Comment by hparfr** [comment]
Hi,

addToCurrentCart does make sense only if the user already has a cart.

In actual version of the bridge the cart is created during the login()
https://github.com/hparfr/prestashopBridge/blob/master/PrestashopBridge.php#L82

If you want to create a cart to guest users, do not hestiate to propose a pull request :)

**Comment by xabikip** [comment]
No, I don't need to create a cart to guest users, and I use the login() function of the bridge before add product to de cart. 

My approach is the next:
- First te user login in my app, at the sime time use the login() function of the bridge to login in PS. (this works well)
- Then the user can click "add product" button in my app, and now is when use the addToCurrentCart() function, but i have the error described above.

Is supposed, if before to add cart I use the login() function should be created Cart. And does not happen.

Do you see any problems in my approach?

**Comment by xabikip** [comment]
Hi,

I don't know why but if put login() before addToCurrentCart(), then work nice. Now i have like that:
$prestaBridge->login($email);
$prestaBridge->addToCurrentCart($id_product, 1, $ref);

I'm confused, because I thought that if I had logged, the context and cart would be created, and would not have to login again.

**Comment by xabikip** [comment]
Hi,

Do you know how to plan to create a cart for guest users? I'm trying to do but not how to raise it, what steps follow.
I'm not asking you to write the code but if I could give me some reference or track how. I hope to achieve and share with you.

**Comment by hparfr** [comment]
I don't plan to write this feature but I accept well written pull requests :)
You can strat by readding the source code of login in Prestashop  to know how they achieve this.

**Comment by xabikip** [comment]
I write this code and work fine: 

//add a product to the cart with quantity and a reference as a GUEST
	public function addToCart($idProduct, $quantity = 1, $ref = null) {
		$ctx = \Context::getContext();//print("\n ctx: ");print_r($ctx);exit;
		$guest = new \Guest();
		$guest->save();
		$ctx->cart = new \Cart();
		$ctx->cart->id_currency = \Currency::getDefaultCurrency()->id;
		$ctx->cart->id_lang = $ctx->language->id;
		$ctx->cart->id_guest = (int)($guest->id);
		$ctx->cart->save();
		$ctx->cookie->id_cart = (int)$ctx->cart->id;//lerro honekin karritoan bistaratzia lortu dut.
		$ctx->cookie->write();
		$cart = $ctx->cart;
		if ($ref) { //do not add twice the same ref
			$customiziations = $ctx->cart->getProductCustomization($idProduct);//print("\n customiziations: ");print_r($customiziations);
			$customWithRef = array_filter($customiziations, function ($c) use ($ref) {
				return $ref == $c['value'];
			});
			if (!$customWithRef) { //not already present
				$cart->addTextFieldToProduct($idProduct, 1, \Product::CUSTOMIZE_TEXTFIELD, $ref);
				$cart->updateQty($quantity, $idProduct);
				$ctx->cookie->write();
			} else { //already present, remplace quantity (if needed)
				$custom = $customWithRef[0];
				$qtyDiff = $quantity - $custom['quantity'];
				$upOrDown = ($qtyDiff >= 0) ? 'up' : 'down'; //updateQty only change relatively
				if ($qtyDiff !== 0)
					$cart->updateQty( abs($qtyDiff), $idProduct, null, $custom['id_customization'], $upOrDown);//print("\n cart: ");print_r($cart);
				$ctx->cookie->write();
			}
		} else
			$cart->updateQty($quantity, $idProduct);
			$ctx->cookie->write();
	}

But the problem is, that if the user close a nav tab or go another site the cart was lost.
