### ISSUE TITLE
Undefined Cache:: methods

### ISSUE THREAD

**Issue by Zythum1984** [hparfr/prestashopBridge#7]
Hi,

I'm trying out your library as it sounds exactly like what I need. However, i can't seem to get past the first instance call. This is the situation:

I have a Concrete5 installation in my root folder
My Prestashop installation resides in a /shop subfolder
I can install everything via composer no problem
Afer including the various setup lines (autoload, USE, new call to class), when i call my login function i get a series of "undefined method" php errors, specifically

- Call to undefined method Cache::isStored() (this I can bypass by activating Prestashop Cache apparently)

-  Call to undefined method Cache::getInstance()

And that's where I'm stuck. I'd really appreciate if you would help me solve this.

Thank you

**Comment by hparfr** [comment]
Hi,

I didn't test it against versions after 1.6.0.14, you can check with an older version to ensure if it's comming from prestashop code changes or from your installation.

**Comment by Zythum1984** [comment]
Thanks for your response.
I tried installing 1.6.0.14 but still no luck, could you perhaps take a look at my controller to see if you can spot anything wrong? I'm including composer autoload and invoking the USE statement as per your instructions. Then i just try to instantiate the new Object inside the do_login method. That's where i get the 

Call to undefined method Cache::isStored()

error

Many thanks in advance
[login.zip.zip](https://github.com/hparfr/prestashopBridge/files/95618/login.zip.zip)

**Comment by hparfr** [comment]
I can't test your code.
You can increase the error level to determine where this error is triggered.
